services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: your_postgres_user #usuario do postgres
      POSTGRES_DB: your_database_name #nome do banco de dados
      POSTGRES_HOST_AUTH_METHOD: trust #autenticação do banco de dados/trust
    ports:
      - "5432:5432" #opcional
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python run.py
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://seu_usuario@db:5432/seu_banco_de_dados 